Layout/MultilineMethodCallIndentation:
  Enabled: false
Lint/Debugger:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.7
