name: Ruby Check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7.x, head]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install --with=dev

      - name: Lint check
        run: rubocop

      - name: Run tests
        run: bundle exec rake
